#docker-compose.yml
version: "2"

#dev
services:
  ehr-backend:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: sampleBackend
    ports:
      - '8000:8000'
    volumes:
      - $PWD/:/app/
    tty: true
    command: python /app/manage.py runserver 0.0.0.0:8000